window:
  padding:
    x: 10
    y: 10
  decorations: none

scrolling:
  history: 10000

font:
  normal:
    family: Fira Code Nerd Font
  size: 13.0

background_opacity: 0.95
live_config_reload: true

# # Colors (One Dark)
# colors:
#   # Default colors
#   primary:
#     background: '0x1e2127'
#     foreground: '0xabb2bf'

#   # Normal colors
#   normal:
#     black:   '0x1e2127'
#     red:     '0xe06c75'
#     green:   '0x98c379'
#     yellow:  '0xd19a66'
#     blue:    '0x61afef'
#     magenta: '0xc678dd'
#     cyan:    '0x56b6c2'
#     white:   '0xabb2bf'

#   # Bright colors
#   bright:
#     black:   '0x5c6370'
#     red:     '0xe06c75'
#     green:   '0x98c379'
#     yellow:  '0xd19a66'
#     blue:    '0x61afef'
#     magenta: '0xc678dd'
#     cyan:    '0x56b6c2'
#     white:   '0xffffff'

# gruvbox
# colors:
#   primary:
#     # hard contrast: background = '0x1d2021'
#     background: '0x282828'
#     # soft contrast: background = '0x32302f'
#     foreground: '0xebdbb2'

#   normal:
#     black: '0x282828'
#     red: '0xcc241d'
#     green: '0x98971a'
#     yellow: '0xd79921'
#     blue: '0x458588'
#     magenta: '0xb16286'
#     cyan: '0x689d6a'
#     white: '0xa89984'

#   bright:
#     black: '0x928374'
#     red: '0xfb4934'
#     green: '0xb8bb26'
#     yellow: '0xfabd2f'
#     blue: '0x83a598'
#     magenta: '0xd3869b'
#     cyan: '0x8ec07c'
#     white: '0xebdbb2'

# # Colors (Nord)
# colors:
#    # Default colors
#    primary:
#      background: '#2E3440'
#      foreground: '#D8DEE9'

#    # Normal colors
#    normal:
#      black:   '#3B4252'
#      red:     '#BF616A'
#      green:   '#A3BE8C'
#      yellow:  '#EBCB8B'
#      blue:    '#81A1C1'
#      magenta: '#B48EAD'
#      cyan:    '#88C0D0'
#      white:   '#E5E9F0'

#    # Bright colors
#    bright:
#      black:   '#4C566A'
#      red:     '#BF616A'
#      green:   '#A3BE8C'
#      yellow:  '#EBCB8B'
#      blue:    '#81A1C1'
#      magenta: '#B48EAD'
#      cyan:    '#8FBCBB'
#      white:   '#ECEFF4'

# Colors (Auroroa)
colors:
   # Default colors
   primary:
     foreground: '#E5E9F0'
     background: '#232731'

   # Normal colors
   normal:
     black:   '#3B4252'
     red:     '#BF616A'
     green:   '#A3BE8C'
     yellow:  '#EBCB8B'
     blue:    '#81A1C1'
     magenta: '#B48EAD'
     cyan:    '#88C0D0'
     white:   '#E5E9F0'

   # Bright colors
   bright:
     black:   '#4C566A'
     red:     '#F44747'
     green:   '#B5CEA8'
     yellow:  '#D7BA7D'
     blue:    '#81A1C1'
     magenta: '#B48EAD'
     cyan:    '#8FBCBB'
     white:   '#ECEFF4'
