font:
  size: 16
  normal:
    family: FuraCode Nerd Font

shell:
  program: /usr/local/bin/zsh
  args:
    - --login

window:
  decorations: none
  padding:
    x: 10
    y: 10

live_config_reload: true

# Colors (Gruvbox dark)
colors:
  primary:
    # hard contrast: background = '#1d2021'
    background: '#282828'
    # soft contrast: background = '#32302f'
    foreground: '#ebdbb2'

  # Normal colors
  normal:
    black: '#282828'
    red: '#cc241d'
    green: '#98971a'
    yellow: '#d79921'
    blue: '#458588'
    magenta: '#b16286'
    cyan: '#689d6a'
    white: '#a89984'

  # Bright colors
  bright:
    black: '#928374'
    red: '#fb4934'
    green: '#b8bb26'
    yellow: '#fabd2f'
    blue: '#83a598'
    magenta: '#d3869b'
    cyan: '#8ec07c'
    white: '#ebdbb2'
